#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2014 OpenWrt.org

START=93
STOP=93

USE_PROCD=1

PROG=/usr/sbin/sound

start_service() {

	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}

curvol(){ echo "$1" | grep -m1 '%' | awk -F'[' '{print$2}' | awk -F'%' '{print $1}'; }
stop_service() {
	MIXERNAME="SoftMaster"
	INIT_VOL="/etc/.soundvolume"
	cur=`curvol "$(amixer sget $MIXERNAME)"`
	echo $cur > ${INIT_VOL}
}
